INSERT INTO products (category_id, name, description, price, unit_of_measure, product_image)
VALUES
(1, 'Pão Francês', '', 1.00, 'un', '/products/pao_frances.png'),
(1, 'Baguete', '', 5.00, 'un', '/products/baguete.png'),
(1, 'Pão de Queijo', '', 4.00, 'un', '/products/pao_de_queijo.png'),
(1, 'Pão Doce', '', 4.00, 'un', '/products/pao_doce.png'),
(1, 'Pão de Banana', '', 20.00, 'un', '/products/pao_de_banana.png'),
(1, 'Pão Integral', '', 17.90, 'un', '/products/pao_integral.png'),
(1, 'Brioche', '', 5.00, 'un', '/products/brioche.png'),
(1, 'Bolacha Caseira', 'Chocolate ou Baunilha', 1.90, 'un', '/products/bolacha_caseira.png'),
(1, 'Muffin de Blueberrys', '', 7.00, 'un', '/products/muffin.png'),
(1, 'Pão de Leite', '', 1.70, 'un', '/products/pao_de_leite.png'),
(1, 'Cafuné', 'Moda da Casa', 30.00, 'un', '/products/cafune.png'),
(1, 'Pão Vegano', '', 18.90, 'un', '/products/pao_vegano.png'),
(2, 'Água', '', 5.50, '310ml', '/products/agua.png'),
(2, 'Suco Natural', '', 10.00, '350ml', '/products/suco_natural.png'),
(3, 'Expresso', 'Americano', 3.50, '30ml', '/products/expresso.png'),
(3, 'Macchiato', '', 8.00, '150ml', '/products/macchiato.png'),
(3, 'Café com Leite', '', 6.00, '150ml', '/products/cafe_com_leite.png'),
(3, 'Cappuccino Chamego', '', 15.50, '200ml', '/products/cappuccino_chamego.png'),
(3, 'Mocaccino Meiguice', '', 10.00, '150ml', '/products/mocaccino_meiguice.png'),
(3, 'Café Gelado', '', 4.00, '150ml', '/products/cafe_gelado.png'),
(3, 'Latte Conforto', 'Latte de baunilha com caramelo bruleé', 16.70, '150ml', '/products/latte_conforto.png'),
(3, 'Frappucino Beijoca', 'Frappuccino de creme de morango', 16.70, '200ml', '/products/frappucino_beijoca.png'),
(4, 'Chá Preto com Limão', '', 5.00, '80ml', '/products/cha_preto.png'),
(4, 'Chá Matcha', '', 6.00, '80ml', '/products/cha_matcha.png'),
(4, 'Chá Gelado', '', 5.00, '80ml', '/products/cha_gelado.png'),
(5, 'Afago', 'Pão ciabatta, tomate, provolone e molho pesto', 22.00, 'un', '/products/afago.png'),
(5, 'Croissant à Caprese', 'Croissant com tomate, muçarela de búfala e manjericão', 21.00, 'un', '/products/croissant_caprese.png'),
(5, 'Ternura', 'Baguete com presunto de parma e burrata', 24.00, 'un', '/products/ternura.png'),
(6, 'Abraço', 'Torta de limão siciliano', 45.00, 'un', '/products/abraco.png'),
(6, 'Mimo', 'Torta de morango', 45.00, 'un', '/products/mimo.png'),
(6, 'Agrado', 'Torta de floresta negra (cereja e chocolate)', 45.00, 'un', '/products/agrado.png'),
(7, 'Bombom de Morango', '', 6.50, 'un', '/products/bombom_de_morango.png'),
(7, 'Bomba de Chocolate', '', 7.00, 'un', '/products/bomba_de_chocolate.png'),
(7, 'Sonho', '', 8.00, 'un', '/products/sonho.png'),
(7, 'Rosca Doce', '', 6.00, 'un', '/products/rosca_doce.png'),
(7, 'Croissant Recheado', '', 15.00, 'un', '/products/croissant_recheado.png'),
(7, 'Quindim', '', 10.00, 'un', '/products/quindim.png'),
(7, 'Panetone', '', 25.90, 'un', '/products/panetone.png'),
(7, 'Cannoli Recheado', '', 15.00, 'un', '/products/cannoli_recheado.png');